@startuml

actor Felhasználó as user
participant ShareOn as site
control "Kréta API" as kreta
database Adatbázis as DB

user->site: felhasználónév\njelszó\nintézmény
site->kreta: nonce lekérése
kreta->site: nonce kód
site->site: AuthorizationPolicy-Key generálása
site->kreta: autentikációs kérés
kreta->kreta: adatfeldolgozás
kreta->site: autentikációs válasz\nBearer token
site->DB: adatbázis frissítése
site->user: tovább léptetés Dashboard-ra

@enduml
